---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: annotationlab-cronjob
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs", "pods"]
  verbs: ["get", "create", "list", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: annotationlab-cronjob
subjects:
- kind: ServiceAccount
  name: annotationlab
  namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: annotationlab-cronjob
  apiGroup: rbac.authorization.k8s.io
