apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: annotationlab
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: annotationlab
    namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: annotationlab
  apiGroup: rbac.authorization.k8s.io