{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "annotationlab.fullname" . }}-network-policy
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  podSelector:
    matchLabels:
     {{- include "annotationlab.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
       matchLabels:
        {{- include "annotationlab.keycloak.selectorLabels" . | nindent 10 }}
    - podSelector:
       matchLabels:
        app.kubernetes.io/instance: training-pod
        app.kubernetes.io/name: training-pod
    - podSelector:
        matchLabels:
          component: worker
          release: {{ include "annotationlab.airflow.fullname" . }}
          tier: airflow
  - from:
{{- if .Values.extraNetworkPolicies }}
{{ .Values.extraNetworkPolicies | indent 4 }}
{{- end }}
    ports:
    - port: 8200
      protocol: TCP
  egress:
  - ports:
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector: {}
    - podSelector: {}
  - ports:
    - port: 5000
      protocol: TCP
  - ports:
    - port: 6443
      protocol: TCP
  - ports:
    - port: 443
      protocol: TCP
  - ports:
    - port: 5432
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ include "annotationlab.fullname" . }}
          app.kubernetes.io/name: postgresql
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ include "annotationlab.fullname" . }}
          app.kubernetes.io/name: airflow-postgresql
  - ports:
    - port: 8080
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          {{- include "annotationlab.keycloak.selectorLabels" . | nindent 10 }}
  - ports:
    - port: 8080
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          component: webserver
          release: {{ include "annotationlab.airflow.fullname" . }}
          tier: airflow
{{- end }}
