apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "annotationlab.fullname" . }}-config
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
data:
  ANNOTATIONLAB_FULLNAME: {{ include "annotationlab.fullname" . }}
  AIRFLOW_DB_HOST: {{ include "annotationlab.airflow.postgresql.fullname" . }}
  KEYCLOAK_REALM_NAME: {{ .Values.configuration.KEYCLOAK_REALM_NAME }}
  NAMESPACE: {{ .Release.Namespace }}
{{- if .Values.ingress.defaultBackend }}
  KEYCLOAK_SERVER_URL: {{ include "annotationlab.keycloak.internal_url" . }}
{{- else }}
  KEYCLOAK_SERVER_URL: {{ include "annotationlab.keycloak.url" . }}
  ANNOTATIONLAB_URL: {{ include "annotationlab.url" . }}
{{- end }}
