{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "annotationlab.fullname" . }}
  labels:
    {{- include "annotationlab.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: '{{ .Values.ingress.uploadLimitInMegabytes }}m'
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.defaultBackend }}
  defaultBackend:
    service:
      name: {{ include "annotationlab.fullname" $ }}
      port:
        name: {{ $.Values.service.portName }}
    {{- if and ($.Values.installKeycloak) (not $.Values.keycloak.ingress.enabled) }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "annotationlab.fullname" $ }}
                port:
                  name: http
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "annotationlab.keycloak.fullname" $ }}-http
                port:
                  name: http
  {{- else }}
    {{- if .Values.ingress.tls }}
  tls:
      {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "annotationlab.fullname" $ }}
                port:
                  name: {{ $.Values.service.portName }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "annotationlab.keycloak.fullname" $ }}-http
                port:
                  name: http
    {{- end }}
  {{- end }}
{{- end }}
