{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: training-pod-policy
spec:
  podSelector:
    matchLabels:
     app.kubernetes.io/instance: training-pod
     app.kubernetes.io/name: training-pod
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
       matchLabels:
        component: worker
        release: {{ include "annotationlab.airflow.fullname" . }}
        tier: airflow
  egress:
  - to:
    - podSelector:
       matchLabels:
        app.kubernetes.io/instance: {{ include "annotationlab.fullname" . }}
        app.kubernetes.io/name: postgresql
    ports:
    - port: 5432
      protocol: TCP
  - to:
    - namespaceSelector: {}
    - podSelector: {}
    ports:
    - port: 53
      protocol: UDP
{{- end }}
