{{- if .Values.celery.enabled -}}
{{- if .Values.celery.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "celery.serviceAccountName" . }}
  labels:
    {{- include "celery.labels" . | nindent 4 }}
  {{- with .Values.celery.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}