{{- if $.Values.celery.enabled -}}
{{- range $queue_name, $val := $.Values.celery.queues }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "celery.fullname" $ }}-{{ $queue_name }}
  labels:
    app.kubernetes.io/name: {{ include "celery.name" $ }}-{{ $queue_name }}
    {{- include "celery.labels" $ | nindent 4 }}
spec:
  replicas: {{ $val.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "celery.name" $ }}-{{ $queue_name }}
      {{- include "celery.selectorLabels" $ | nindent 6 }}
  {{- with $.Values.celery.deploymentStrategy }}
  strategy:
  {{ toYaml . | trim | indent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with $.Values.celery.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "celery.name" $ }}-{{ $queue_name }}
        {{- include "celery.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "celery.serviceAccountName" $ }}
      {{- if $.Values.celery.podSecurityContext.enabled }}
      securityContext: {{- omit $.Values.celery.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ $.Values.celery.automountServiceAccountToken }}
      containers:
        - name: celery
          image: "{{ $.Values.global.image.repository }}:{{ $.Values.global.image.tag | default $.Chart.AppVersion }}"
          args: [ "celery", "worker", "-l", "INFO", "-E", "-A", "escriptorium", "-Ofair", "--prefetch-multiplier", "1", "-c", "1", "-Q", {{ $val.args }} ]
          imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
          {{- if $.Values.celery.containerSecurityContext.enabled }}
          securityContext: {{- omit $.Values.celery.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          env:
            {{- template "app.common.envs" $ }}
            {{- if $.Values.celery.extraEnvironmentVars -}}
            {{- range $key, $value := $.Values.celery.extraEnvironmentVars }}
            - name: {{ printf "%s" $key | replace "." "_" | upper | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- if $.Values.celery.extraEnvironmentSecrets -}}
            {{- range $key, $value := $.Values.celery.extraEnvironmentSecrets }}
            - name: {{ printf "%s" $key | replace "." "_" | upper | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretName }}
                  key: {{ $value.secretKey }}
            {{- end }}
            {{- end }}
            {{- if or $.Values.celery.cmdWrapper $.Values.global.cmdWrapper }}
            - name: CMD_WRAPPER
              value: {{ coalesce $.Values.celery.cmdWrapper $.Values.global.cmdWrapper }}
            {{- end }}
          ports:
            - name: service
              containerPort: 8000
              protocol: TCP
          {{- if $.Values.celery.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $.Values.celery.readinessProbe.path | quote }}
              port: 8000
            failureThreshold: {{ $.Values.celery.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ $.Values.celery.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.celery.readinessProbe.periodSeconds }}
            successThreshold: {{ $.Values.celery.readinessProbe.successThreshold }}
            timeoutSeconds: {{ $.Values.celery.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if $.Values.celery.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ $.Values.celery.livenessProbe.path | quote }}
              port: 8000
            failureThreshold: {{ $.Values.celery.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ $.Values.celery.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.celery.livenessProbe.periodSeconds }}
            successThreshold: {{ $.Values.celery.livenessProbe.successThreshold }}
            timeoutSeconds: {{ $.Values.celery.livenessProbe.timeoutSeconds }}
          {{- end }}
          resources:
          {{- if $val.resources }}
            {{- toYaml $val.resources | nindent 12 }}
          {{- else }}
            {{- toYaml $.Values.celery.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: media
              mountPath: /usr/src/app/media
            - name: static
              mountPath: /usr/src/app/static
            {{- if $.Values.global.pgConfig.ssl.pgSslSecretName }}
            - name: pg-ssl-certs
              mountPath: /opt/heartex/secrets/pg_certs
            {{- end }}
            {{- if $.Values.global.redisConfig.ssl.redisSslSecretName }}
            - name: redis-ssl-certs
              mountPath: /opt/heartex/secrets/redis_certs
            {{- end }}
            {{- if $.Values.app.extraVolumeMounts }}
              {{ toYaml $.Values.app.extraVolumeMounts | nindent 12 }}
            {{- end }}
            {{- if $.Values.celery.extraVolumeMounts }}
              {{ toYaml $.Values.celery.extraVolumeMounts | nindent 12 }}
            {{- end }}
      {{- with $.Values.celery.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $.Values.celery.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "tplvalues.render" (dict "value" $.Values.celery.topologySpreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      {{- if $.Values.celery.dnsPolicy }}
      dnsPolicy: {{ $.Values.celery.dnsPolicy }}
      {{- end }}
      {{- if $.Values.celery.enableServiceLinks }}
      enableServiceLinks: {{ $.Values.celery.enableServiceLinks }}
      {{- end }}
      {{- if $.Values.celery.shareProcessNamespace }}
      shareProcessNamespace: {{ $.Values.celery.shareProcessNamespace }}
      {{- end }}
      {{- with $.Values.celery.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.celery.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: media
          {{- if and $.Values.global.persistence.enabled (eq $.Values.global.persistence.type "volume") }}
          persistentVolumeClaim:
            claimName: {{ include "pvc.claimName" $ }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: static
          emptyDir: {}    
        {{- if $.Values.global.pgConfig.ssl.pgSslSecretName }}
        - name: pg-ssl-certs
          secret:
            secretName: {{ $.Values.global.pgConfig.ssl.pgSslSecretName }}
            defaultMode: 0640
        {{- end }}
        {{- if $.Values.global.redisConfig.ssl.redisSslSecretName }}
        - name: redis-ssl-certs
          secret:
            secretName: {{ $.Values.global.redisConfig.ssl.redisSslSecretName  }}
            defaultMode: 0640
        {{- end }}
        {{- if $.Values.app.extraVolumes -}}
          {{- toYaml $.Values.app.extraVolumes | nindent 8 }}
        {{- end }}

        {{- if $.Values.celery.extraVolumes -}}
          {{- toYaml $.Values.celery.extraVolumes | nindent 8 }}
        {{- end }}
{{- end }}
{{- end }}