apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-chart-info
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  escriptoriumVersion: "{{ coalesce .Values.global.image.tag .Chart.AppVersion }}"
  escriptoriumChartVersion: "{{ .Chart.Version }}"
