apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-nginxconfig
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  default.conf: |-
{{- if .Values.app.nginx.config.default }}
    upstream escriptorium {
        server 127.0.0.1:8000;
        # server unix:/usr/src/app/escriptorium/app.sock;
    }

    server {
        listen 8080;
        charset     utf-8;
        client_max_body_size 150M;

        gzip_static  on;
        gzip on;
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
        include /etc/nginx/mime.types;

        location /nginx_health {
            return 200;
        }

        location / {
            uwsgi_pass  escriptorium;
            include     uwsgi_params;
            uwsgi_param HTTP_X_FORWARDED_PROTO $scheme;

            proxy_pass http://escriptorium;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
        }

        location /static/ {
            alias /usr/src/app/static/;
        }

        location /favicon.ico {
            alias /usr/src/app/static/images/favicon.ico;
        }

        location /media/ {
            alias /usr/src/app/media/;
        }

        location = /robots.txt {
            alias /usr/src/app/static/robots.txt;
        }
    }
{{- else }}
{{ .Values.app.nginx.config.custom | indent 4 }}
{{- end }}