apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
{{- if not .Values.global.extraEnvironmentSecrets.SECRET_KEY }}
  django-secret-key: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
{{- if not .Values.global.extraEnvironmentSecrets.DJANGO_SU_PASSWORD }}
  django-su-password: {{ randAlphaNum 8 | b64enc | quote }}
{{- end }}