# eScriptorium with external RDS instance deployed in us-east-1 AWS region
# Nginx-ingress used as an Ingress Controller
# Cert-manager to handle certificates

global:
  redisConfig:
    host: "redis"
  pgConfig:
    host: "eScriptorium-123as.cluster-1111.us-east-1.rds.amazonaws.com"
    dbName: "postgres"
    userName: "root"
    password:
      secretName: "postgresql"
      secretKey: "postgresql-password"

app:
  ingress:
    enabled: true
    host: test.dev.eScriptorium.com
    
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    tls:
      - secretName: test.dev.eScriptorium.com
        hosts:
          - dev.eScriptorium.com

postgresql:
  enabled: false

redis:
  enabled: false
  
ci: true

